/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CommentId = bigint;
export type ConversationId = bigint;
export interface ConversationView {
  'id' : ConversationId,
  'participant1' : UserId,
  'participant2' : UserId,
  'messages' : Array<Message>,
}
export interface EmployeeView {
  'id' : UserId,
  'username' : string,
  'city' : string,
  'state' : string,
  'photo' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : UserId,
  'timestamp' : Time,
}
export type MessageId = bigint;
export type Orientation = { 'top' : null } |
  { 'lesbian' : null } |
  { 'bottom' : null } |
  { 'versatile' : null };
export interface PhotoPost { 'caption' : string, 'photo' : ExternalBlob }
export interface Post {
  'id' : PostId,
  'likeCount' : bigint,
  'content' : PostContent,
  'author' : UserId,
  'timestamp' : Time,
  'commentCount' : bigint,
}
export interface PostComment {
  'id' : CommentId,
  'content' : string,
  'author' : UserId,
  'timestamp' : Time,
  'postId' : PostId,
}
export type PostContent = { 'text' : TextPost } |
  { 'photo' : PhotoPost };
export type PostId = bigint;
export type RelationshipStatus = { 'fun' : null } |
  { 'looking' : null } |
  { 'casual' : null };
export type Subscription = { 'pro' : null } |
  { 'free' : null };
export interface TextPost { 'content' : string }
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'messageCountDaily' : bigint,
  'lastActivityDay' : bigint,
  'username' : string,
  'subscription' : Subscription,
  'interests' : Array<Orientation>,
  'city' : string,
  'lookingFor' : Array<RelationshipStatus>,
  'state' : string,
  'gender' : Gender,
  'isAdmin' : boolean,
  'photo' : [] | [ExternalBlob],
  'postCountDaily' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentPost' : ActorMethod<[PostId, string], undefined>,
  'createPhotoPost' : ActorMethod<[ExternalBlob, [] | [string]], undefined>,
  'createPost' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAllConversations' : ActorMethod<[], Array<ConversationView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[UserId], [] | [Array<Message>]>,
  'getEmployees' : ActorMethod<[], Array<EmployeeView>>,
  'getFeed' : ActorMethod<[], Array<Post>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getPostComments' : ActorMethod<[PostId], Array<PostComment>>,
  'getPostsByUser' : ActorMethod<[UserId], Array<Post>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[UserId, string], undefined>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'uploadPhoto' : ActorMethod<[ExternalBlob, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];