/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : UserId,
  'timestamp' : Time,
});
export const ConversationView = IDL.Record({
  'id' : ConversationId,
  'participant1' : UserId,
  'participant2' : UserId,
  'messages' : IDL.Vec(Message),
});
export const Subscription = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});
export const Orientation = IDL.Variant({
  'top' : IDL.Null,
  'lesbian' : IDL.Null,
  'bottom' : IDL.Null,
  'versatile' : IDL.Null,
});
export const RelationshipStatus = IDL.Variant({
  'fun' : IDL.Null,
  'looking' : IDL.Null,
  'casual' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'messageCountDaily' : IDL.Nat,
  'lastActivityDay' : IDL.Int,
  'username' : IDL.Text,
  'subscription' : Subscription,
  'interests' : IDL.Vec(Orientation),
  'city' : IDL.Text,
  'lookingFor' : IDL.Vec(RelationshipStatus),
  'state' : IDL.Text,
  'gender' : Gender,
  'isAdmin' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
  'postCountDaily' : IDL.Nat,
});
export const EmployeeView = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const TextPost = IDL.Record({ 'content' : IDL.Text });
export const PhotoPost = IDL.Record({
  'caption' : IDL.Text,
  'photo' : ExternalBlob,
});
export const PostContent = IDL.Variant({
  'text' : TextPost,
  'photo' : PhotoPost,
});
export const Post = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'content' : PostContent,
  'author' : UserId,
  'timestamp' : Time,
  'commentCount' : IDL.Nat,
});
export const CommentId = IDL.Nat;
export const PostComment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
  'postId' : PostId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentPost' : IDL.Func([PostId, IDL.Text], [], []),
  'createPhotoPost' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [], []),
  'createPost' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getAllConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [UserId],
      [IDL.Opt(IDL.Vec(Message))],
      ['query'],
    ),
  'getEmployees' : IDL.Func([], [IDL.Vec(EmployeeView)], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
  'getPostComments' : IDL.Func([PostId], [IDL.Vec(PostComment)], ['query']),
  'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'uploadPhoto' : IDL.Func([ExternalBlob, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : UserId,
    'timestamp' : Time,
  });
  const ConversationView = IDL.Record({
    'id' : ConversationId,
    'participant1' : UserId,
    'participant2' : UserId,
    'messages' : IDL.Vec(Message),
  });
  const Subscription = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const Orientation = IDL.Variant({
    'top' : IDL.Null,
    'lesbian' : IDL.Null,
    'bottom' : IDL.Null,
    'versatile' : IDL.Null,
  });
  const RelationshipStatus = IDL.Variant({
    'fun' : IDL.Null,
    'looking' : IDL.Null,
    'casual' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'messageCountDaily' : IDL.Nat,
    'lastActivityDay' : IDL.Int,
    'username' : IDL.Text,
    'subscription' : Subscription,
    'interests' : IDL.Vec(Orientation),
    'city' : IDL.Text,
    'lookingFor' : IDL.Vec(RelationshipStatus),
    'state' : IDL.Text,
    'gender' : Gender,
    'isAdmin' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
    'postCountDaily' : IDL.Nat,
  });
  const EmployeeView = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const TextPost = IDL.Record({ 'content' : IDL.Text });
  const PhotoPost = IDL.Record({
    'caption' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const PostContent = IDL.Variant({ 'text' : TextPost, 'photo' : PhotoPost });
  const Post = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'content' : PostContent,
    'author' : UserId,
    'timestamp' : Time,
    'commentCount' : IDL.Nat,
  });
  const CommentId = IDL.Nat;
  const PostComment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
    'postId' : PostId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentPost' : IDL.Func([PostId, IDL.Text], [], []),
    'createPhotoPost' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [], []),
    'createPost' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getAllConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [UserId],
        [IDL.Opt(IDL.Vec(Message))],
        ['query'],
      ),
    'getEmployees' : IDL.Func([], [IDL.Vec(EmployeeView)], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(Post)], ['query']),
    'getPostComments' : IDL.Func([PostId], [IDL.Vec(PostComment)], ['query']),
    'getPostsByUser' : IDL.Func([UserId], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'uploadPhoto' : IDL.Func([ExternalBlob, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };